name: Execute SSH Commands

on:
  workflow_dispatch: # 手动触发工作流
  schedule:
    - cron: "0 15 * * *"  # 每天15点运行一次

jobs:
  execute-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y jq sshpass

      - name: Load Accounts
        id: load-accounts
        run: |
          echo "$ACCOUNTS_JSON" > accounts.json
        env:
          ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}

      - name: Execute SSH Commands
        run: |
          while IFS= read -r account; do
            username=$(echo "$account" | jq -r '.username')
            password=$(echo "$account" | jq -r '.password')
            ssh=$(echo "$account" | jq -r '.ssh')
            echo "Executing command for $username@$ssh..."
            sshpass -p "$password" ssh -t -o StrictHostKeyChecking=no "$username@$ssh" 'bash <(curl -s https://github.com/mi1314cat/serv00-GPTsh/raw/refs/heads/main/crtest.sh)'
          done < <(jq -c '.[]' accounts.json)
        env:
          ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
